/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz1diri;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author tm_galli
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tituloventana = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        partidos = new javax.swing.JLabel();
        listapartidos = new javax.swing.JComboBox<>();
        cambiofecha = new javax.swing.JButton();
        borrarfecha = new javax.swing.JButton();
        agrefecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(99, 140, 181));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(99, 140, 181));

        tituloventana.setFont(new java.awt.Font("Waree", 0, 18)); // NOI18N
        tituloventana.setText("Agenda de eventos");

        jButton1.setBackground(new java.awt.Color(182, 192, 199));
        jButton1.setText("<--");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloventana, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tituloventana, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        partidos.setFont(new java.awt.Font("Waree", 0, 14)); // NOI18N
        partidos.setText("Partidos");

        listapartidos.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        listapartidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listapartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listapartidosActionPerformed(evt);
            }
        });

        cambiofecha.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        cambiofecha.setText("Cambiar fecha");
        cambiofecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiofechaActionPerformed(evt);
            }
        });

        borrarfecha.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        borrarfecha.setText("Borrar fechas");
        borrarfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarfechaActionPerformed(evt);
            }
        });

        agrefecha.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        agrefecha.setText("Agregar fecha");
        agrefecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agrefechaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Waree", 0, 14)); // NOI18N
        jLabel1.setText("Que quieres hacer?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cambiofecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agrefecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(borrarfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partidos)
                            .addComponent(listapartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(182, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(partidos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listapartidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cambiofecha, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agrefecha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrarfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarfechaActionPerformed
        Borrarfecha borrar=new Borrarfecha();
        borrar.setLocation(0,0);
        borrar.setSize(520,400);
        this.setVisible(false);
        borrar.setVisible(true);
        //borrar.setBounds(200,200,500,500);
    }//GEN-LAST:event_borrarfechaActionPerformed

    private void cambiofechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiofechaActionPerformed
        Cambiofecha cambio = new Cambiofecha();
        cambio.setSize(600,400);
        cambio.setLocation(0,0);
        this.setVisible(false);
        
        cambio.setVisible(true);
        //cambio.setBounds(200,200,500,500);
    }//GEN-LAST:event_cambiofechaActionPerformed

    private void agrefechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agrefechaActionPerformed
        Agregafecha agregar= new Agregafecha();
        agregar.setSize(600,450);
        agregar.setLocation(0,0);
        this.setVisible(false);
        agregar.setVisible(true);
    }//GEN-LAST:event_agrefechaActionPerformed

    private void listapartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listapartidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listapartidosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pantprincipal pantallita = new pantprincipal();
        pantallita.setSize(675,480);
        this.setVisible(false);
        pantallita.setLocation(0,0);
        pantallita.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
     private List<java.util.Date> Calendario() {
        Connection con = null;
        PreparedStatement pstUsuario = null;
        ResultSet rsUsuario = null;
        List<java.util.Date> listaFechas = new ArrayList<>(); // Cambiar el tipo a java.util.Date si necesitas usarlo fuera de SQL
   
    try {
        con = DatabaseConnection.getConnection(); // Método para obtener conexión a la base de datos
       
        // Consulta para obtener los datos de la tabla
        String queryUsuario = "SELECT Calendario FROM calendario"; // Asegúrate de que "cargos" sea la columna que contiene fechas
        pstUsuario = con.prepareStatement(queryUsuario);
        rsUsuario = pstUsuario.executeQuery();

        java.sql.Date fechaSQL = rsUsuario.getDate("Fecha");
        java.util.Date fechaUtil = new java.util.Date(fechaSQL.getTime());
        listaFechas.add(fechaUtil); // Agregar la fecha convertida a la lista
        
           
       
    } catch (SQLException e) {
        e.printStackTrace(); // Imprimir error
    } finally {
        // Cerrar conexiones
        try {
            if (rsUsuario != null) rsUsuario.close();
            if (pstUsuario != null) pstUsuario.close();
            if (con != null) con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    return listaFechas; 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pantprincipal pant1 = new pantprincipal();
                pant1.setLocation(0,0);
                pant1.setVisible(true);
                new Agenda().setVisible(false);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agrefecha;
    private javax.swing.JButton borrarfecha;
    private javax.swing.JButton cambiofecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> listapartidos;
    private javax.swing.JLabel partidos;
    private javax.swing.JLabel tituloventana;
    // End of variables declaration//GEN-END:variables
}
